service: xploristo

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 8081
      
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  environment:
    NODE_OPTIONS: --experimental-json-modules
    # https://www.serverless.com/plugins/serverless-dotenv-plugin
  httpApi:
    cors:
      allowedOrigins:
        - http://xploristo.s3-website-eu-west-1.amazonaws.com
      allowCredentials: true
      maxAge: 6000 # In seconds
   
functions:
  app:
    handler: src/app.asyncHandler
    events:
      - httpApi: '*'
